language: ruby
sudo: false
bundler_args: --without development
script: "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.6
  - 2.2.2

env:
  - "CHECK=spec"
  - "CHECK=commits"

matrix:
  exclude:
    - rvm: 2.2.2
      env: "CHECK=commits"
    - rvm: 2.0.0
      env: "CHECK=commits"
    - rvm: 1.9.3
      env: "CHECK=commits"
